"""empty message

Revision ID: 1aee9796c254
Revises: 6855a04c9e83
Create Date: 2023-05-22 08:41:09.251121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1aee9796c254'
down_revision = '6855a04c9e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomecategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incomecategory_id', sa.Integer(), nullable=True))
        batch_op.alter_column('dateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_foreign_key(None, 'incomecategory', ['incomecategory_id'], ['id'])
        batch_op.drop_column('category_income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_income', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('dateTime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('incomecategory_id')

    op.drop_table('incomecategory')
    # ### end Alembic commands ###
