"""empty message

Revision ID: 2bfa3f03fba3
Revises: a5109800ecae
Create Date: 2023-05-19 11:14:52.204127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfa3f03fba3'
down_revision = 'a5109800ecae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('type_name', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['type_name'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['category_name'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_name')
        batch_op.drop_column('category_name')

    op.drop_table('type')
    op.drop_table('category')
    # ### end Alembic commands ###
